export const SECTIONS = [
  {
    id: 'manager_walkdown',
    title: 'Manager Daily Walk Down',
    items: [
      { id: 'mw_1', text: "Manager's Daily Walk Down Available and Accurate" },
    ],
  },
  {
    id: 'outside',
    title: 'Outside',
    items: [
      { id: 'out_1', text: 'Pumps clean and free of spiders/spider webs' },
      { id: 'out_2', text: 'Octane decals in place', critical: true },
      { id: 'out_3', text: 'All POP current for branded locations' },
      { id: 'out_4', text: 'All window signs current, not faded, in good repair, no hand written or permanent computer generated signs' },
      { id: 'out_5', text: 'Credit card applications available at the pumps (Chevron/Texaco)' },
      { id: 'out_6', text: 'Receipt paper in all pump crind printers' },
      { id: 'out_7', text: 'Windshield wells: squeegee, towels, water available' },
      { id: 'out_8', text: 'Oil Dry cleaned up and properly disposed' },
      { id: 'out_9', text: 'Exterior trash cans clean and emptied if needed' },
      { id: 'out_10', text: 'Landscaping free of trash and well maintained' },
      { id: 'out_11', text: 'Lot free of trash and litter' },
      { id: 'out_12', text: 'Air/Vac machine operational', critical: true },
      { id: 'out_13', text: 'Dumpster secure. No trash on the ground. Gate closed' },
      { id: 'out_14', text: 'Lot free of trip hazards, water hoses, cords, brooms, etc.' },
      { id: 'out_15', text: 'Windows, ledges, and front door clean' },
      { id: 'out_16', text: 'Ice merchandiser clean and stocked' },
      { id: 'out_17', text: "Smoker's pot clean and emptied" },
      { id: 'out_18', text: 'Propane cage clean' },
      { id: 'out_19', text: 'Parking lot/drive clean' },
      { id: 'out_20', text: 'Front sidewalk clean and free of trip hazards' },
    ],
  },
  {
    id: 'customer_service',
    title: 'Customer Service',
    items: [
      { id: 'cs_1', text: 'Employees in uniform with name tags' },
      { id: 'cs_2', text: 'Employees well groomed in accordance with company policy' },
      { id: 'cs_3', text: "Customers are greeted \"Welcome to Keith's\" as they enter the store" },
      { id: 'cs_4', text: 'Employees offer a suggestive sell to the customer' },
      { id: 'cs_5', text: 'Employees are friendly and check out customers quickly' },
      { id: 'cs_6', text: 'Customers are offered a receipt' },
      { id: 'cs_7', text: "Customers are told, \"Thank you for shopping at Keith's\"" },
      { id: 'cs_8', text: 'Loyalty program offered to customers' },
      { id: 'cs_9', text: 'Loyalty specials highlighted to customers' },
      { id: 'cs_10', text: 'Loyalty promotion signage in place and current' },
    ],
  },
  {
    id: 'sales_floor',
    title: 'Sales Floor',
    items: [
      { id: 'sf_1', text: 'Old tape removed from windows' },
      { id: 'sf_2', text: 'Windows and ledges clean' },
      { id: 'sf_3', text: 'Floor mats clean and in place' },
      { id: 'sf_4', text: 'Floors clean and all gum removed' },
      { id: 'sf_5', text: 'Floors clean behind displays in front of windows and in corners' },
      { id: 'sf_6', text: 'Wet Floor signs used only when the floors are wet' },
      { id: 'sf_7', text: 'Wet Floor signs, mops, brooms, dust pans kept in store room' },
      { id: 'sf_8', text: 'All stock put up and not stacked on the sales floor' },
      { id: 'sf_9', text: 'Shelf merchandise fronted, faced, stocked' },
      { id: 'sf_10', text: 'Shelf merchandise out of stocks noted' },
      { id: 'sf_11', text: 'Sales floor merchandise priced' },
      { id: 'sf_12', text: 'Sales floor merchandise out of dates pulled' },
      { id: 'sf_13', text: 'Novelty merchandise fronted, faced, stocked' },
      { id: 'sf_14', text: 'Novelty merchandise priced' },
      { id: 'sf_15', text: 'Novelty merchandise out of dates pulled' },
      { id: 'sf_16', text: 'Gondola shelves clean' },
      { id: 'sf_17', text: 'Only authorized floor displays in place' },
      { id: 'sf_18', text: 'Floor displays stocked and price signage in place' },
      { id: 'sf_19', text: 'Floors free of trip hazards' },
      { id: 'sf_20', text: 'Check out counters clean and free of clutter' },
      { id: 'sf_21', text: 'Only approved items on the counter' },
      { id: 'sf_22', text: 'Credit card applications available at check out' },
      { id: 'sf_23', text: 'Window signs and displays allow clear visibility to pumps' },
      { id: 'sf_24', text: 'Trash cans clean and emptied if needed' },
      { id: 'sf_25', text: 'Credit merchandise sorted and organized' },
      { id: 'sf_26', text: 'Doors leading to the back rooms closed' },
    ],
  },
  {
    id: 'coolers',
    title: 'Coolers',
    items: [
      { id: 'cl_1', text: 'Cooler merchandise fronted, faced, stocked' },
      { id: 'cl_2', text: 'Cooler merchandise out of stocks noted' },
      { id: 'cl_3', text: 'Cooler merchandised according to the planogram' },
      { id: 'cl_4', text: 'Cooler merchandise priced' },
      { id: 'cl_5', text: 'Cooler merchandise out of dates pulled' },
      { id: 'cl_6', text: 'Cooler doors, ledges, and racks cleaned' },
      { id: 'cl_7', text: 'Cooler backstock neatly stacked and organized' },
      { id: 'cl_8', text: 'Cooler backstock adequate' },
      { id: 'cl_9', text: 'Cooler floors clean' },
      { id: 'cl_10', text: 'No product on the floor underneath the bottom shelf of the cooler rack' },
      { id: 'cl_11', text: 'Cooler door signs are for "new products" or "promotional products"' },
      { id: 'cl_12', text: 'Beer Cave merchandise organized and price signs current' },
    ],
  },
  {
    id: 'restrooms',
    title: 'Restrooms',
    items: [
      { id: 'rt_1', text: 'Restroom toilets, urinals, sinks, floors clean' },
      { id: 'rt_2', text: 'Soap, paper, urinal screens, and supplies stocked' },
      { id: 'rt_3', text: 'Walls and fixtures free of graffiti' },
      { id: 'rt_4', text: 'Trash cans clean and emptied if needed' },
    ],
  },
  {
    id: 'coffee_fountain_foodservice',
    title: 'Coffee/Fountain/Food Service',
    items: [
      { id: 'cf_1', text: 'Coffee and Cappuccino available and fresh' },
      { id: 'cf_2', text: 'Coffee and Cappuccino cups, lids, straws, condiments stocked' },
      { id: 'cf_3', text: 'Coffee, Cappuccino, condiment machines clean' },
      { id: 'cf_4', text: 'Coffee bar clean. No cleaning towels left on the counter' },
      { id: 'cf_5', text: 'Price signs and menus in good repair and current' },
      { id: 'cf_6', text: 'All Fountain and frozen products available' },
      { id: 'cf_7', text: 'Fountain and frozen cups, straws, lids stocked' },
      { id: 'cf_8', text: 'Fountain and frozen machines clean' },
      { id: 'cf_9', text: 'Fountain bar clean. No cleaning towels left on the counter' },
      { id: 'cf_10', text: 'Soft Serve machine clean and sanitized according to schedule' },
      { id: 'cf_11', text: 'Toppings bar clean and well stocked' },
      { id: 'cf_12', text: 'Booth/bar seating areas clean and napkins available' },
      { id: 'cf_13', text: 'Food Service products fresh, well displayed and available' },
      { id: 'cf_14', text: 'Food Service display cases clean, organized, and stocked' },
      { id: 'cf_15', text: 'Food being held at the proper temperature and time' },
      { id: 'cf_16', text: 'All chemicals stored properly' },
      { id: 'cf_17', text: 'All dry goods stored properly and organized' },
      { id: 'cf_18', text: 'All refrigerated product stored and labeled properly. Rotated. Organized' },
      { id: 'cf_19', text: 'All frozen product stored and labeled properly. Rotated. Organized' },
      { id: 'cf_20', text: 'All food handling and sanitation rules and policies being followed' },
      { id: 'cf_21', text: 'Food Service supplies stocked and available' },
      { id: 'cf_22', text: 'Food Service price signs in good repair, operational, and current' },
    ],
  },
  {
    id: 'maintenance',
    title: 'Maintenance',
    isMaintenance: true,
    note: '* 1 Point deduction for each maintenance issue not reported and logged on the Maintenance Dispatch Log',
    items: [
      { id: 'mt_1', text: 'All lights burning on the ID and Price sign', critical: true },
      { id: 'mt_2', text: 'All canopy lights burning', critical: true },
      { id: 'mt_3', text: 'All strip lights burning around the building and canopy', critical: true },
      { id: 'mt_4', text: 'All pumps working', critical: true },
      { id: 'mt_5', text: 'Canopy Uprights and pump bollards clean. Paint in good repair', critical: true },
      { id: 'mt_6', text: 'Parking stripes in good repair', critical: true },
      { id: 'mt_7', text: 'Pump hoses in good repair', critical: true },
      { id: 'mt_8', text: 'All nozzles in good repair', critical: true },
      { id: 'mt_9', text: 'Nozzle boots and splash guard in good repair', critical: true },
      { id: 'mt_10', text: 'Pot holes on lot', critical: true },
      { id: 'mt_11', text: 'All lights working throughout store', critical: true },
      { id: 'mt_12', text: 'Cooler temperature is correct', critical: true },
      { id: 'mt_13', text: 'Cooler door lights working', critical: true },
      { id: 'mt_14', text: 'Hand dryers working', critical: true },
      { id: 'mt_15', text: 'Automatic toilet/urinal flush working', critical: true },
      { id: 'mt_16', text: 'Automatic sink faucet working', critical: true },
      { id: 'mt_17', text: 'Changing tables good repair', critical: true },
      { id: 'mt_18', text: 'Kitchen cooler and freezer at the correct temperature', critical: true },
      { id: 'mt_19', text: 'Coffee and cappuccino machines working properly', critical: true },
      { id: 'mt_20', text: 'Creamer machines working properly', critical: true },
      { id: 'mt_21', text: 'Frozen drink machines working properly', critical: true },
      { id: 'mt_22', text: 'Soft serve ice cream machines working', critical: true },
      { id: 'mt_23', text: 'All food service display and cooking equipment working properly', critical: true },
      { id: 'mt_24', text: 'Other:', critical: true, hasTextField: true },
      { id: 'mt_25', text: 'Other:', critical: true, hasTextField: true },
    ],
  },
];

export function calcScore(answers) {
  const allItems = SECTIONS.flatMap(s => s.items);
  const total = allItems.length;
  const correct = allItems.filter(item => answers[item.id] === 'yes').length;
  const pct = total > 0 ? (correct / total) * 100 : 0;

  let grade = 0;
  if (pct >= 95) grade = 100;
  else if (pct >= 90) grade = 90;
  else if (pct >= 85) grade = 80;

  return { total, correct, pct, grade };
}
